### ISSUE TITLE
Team coding service setting

### ISSUE THREAD

**Issue by ohju96** [JeongSeonggil/COSMOS#24]
## 📌 기능 설명
모여서 각자 코딩(Team coding) 서비스 생성 및 셋팅

## 📑 완료 조건
- [x] create team coding service
- [x] team coding service setting

**Comment by JeongSeonggil** [comment]
@ohju96 
파일 위치 변경

**Comment by ohju96** [comment]
@JeongSeonggil 
확인 후 수정 했습니다.
검토 부탁드립니다.
